// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi7Pf0-KGcG3cm-yVEzjwlyfcejp8pJCo',
    appId: '1:842264331235:web:17296b5972d03429e416d6',
    messagingSenderId: '842264331235',
    projectId: 'fir-tutorial-app-a0c55',
    authDomain: 'fir-tutorial-app-a0c55.firebaseapp.com',
    storageBucket: 'fir-tutorial-app-a0c55.appspot.com',
    measurementId: 'G-13ZX3WJX7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKvVRvZjBiLtVYJ30YfGA7uAtzAedbJ1Y',
    appId: '1:842264331235:android:cada1cba3f2b3cdee416d6',
    messagingSenderId: '842264331235',
    projectId: 'fir-tutorial-app-a0c55',
    storageBucket: 'fir-tutorial-app-a0c55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1gFpG4otORKnhnPkl3CEehSIpWYVJwXM',
    appId: '1:842264331235:ios:3f6fab80ceb2cfeae416d6',
    messagingSenderId: '842264331235',
    projectId: 'fir-tutorial-app-a0c55',
    storageBucket: 'fir-tutorial-app-a0c55.appspot.com',
    iosClientId: '842264331235-4o6qelhpsldmeuea4sfkjacd2ib63gd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1gFpG4otORKnhnPkl3CEehSIpWYVJwXM',
    appId: '1:842264331235:ios:3f6fab80ceb2cfeae416d6',
    messagingSenderId: '842264331235',
    projectId: 'fir-tutorial-app-a0c55',
    storageBucket: 'fir-tutorial-app-a0c55.appspot.com',
    iosClientId: '842264331235-4o6qelhpsldmeuea4sfkjacd2ib63gd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorialApp',
  );
}
